import type { NextPage } from 'next';
import moment from 'moment';
import Head from 'next/head';
import { Time } from './timer';
import hours from './mocks/hours';
import minutes from './mocks/minutes';
import Clock from './components/Clock';
import Testing from './components/Testing';
import { ChangeEvent, useEffect, useState, useCallback } from 'react';
import {
  Box,
  Container,
  Select,
  MenuItem,
  TextField,
  Stack,
  Button,
} from '@mui/material';

const Home: NextPage = () => {
  const [targetTime, setTargetTime] = useState<any>({
    hours: 0,
    minutes: 0,
  });
  const [countdownTime, setCountDownTime] = useState<Time>({
    hours: 0,
    minutes: 0,
    second: 0,
  });

  const [[hrs, mins, secs], setTime] = useState([
    countdownTime.hours,
    countdownTime.minutes,
    countdownTime.second,
  ]);
  const [millisecond, setMillisecond] = useState<number>(0);
  const [enable, setEnable] = useState<boolean>(false);
  const [searchText, setSearchText] = useState<string>('');

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setSearchText(e.target.value);
  };

  const resetCountDownTime = useCallback(
    () => setTime([countdownTime.hours, countdownTime.minutes, countdownTime.second]),
    [countdownTime.hours, countdownTime.minutes, countdownTime.second]
  );

  const tick = useCallback(() => {
    if (hrs === 0 && mins === 0 && secs === 0) resetCountDownTime();
    else if (mins === 0 && secs === 0) {
      setTime([hrs - 1, 59, 59]);
    } else if (secs === 0) {
      setTime([hrs, mins - 1, 59]);
    } else {
      setTime([hrs, mins, secs - 1]);
    }
  }, [hrs, mins, resetCountDownTime, secs]);

  useEffect(() => {
    let timeInterval: any = null;
    if (enable) {
      timeInterval = setInterval(() => tick(), 1000);
    } else {
      clearInterval(timeInterval);
    }

    return () => clearInterval(timeInterval);
  }, [enable, hrs, mins, secs, tick]);

  const handleChangeTime = (e: any, type: string) => {
    switch (type) {
      case 'hours':
        setTargetTime({
          ...targetTime,
          hours: Number(e.target.value),
        });
        break;
      case 'minutes':
        setTargetTime({
          ...targetTime,
          minutes: Number(e.target.value),
        });
        break;

      default:
        return;
    }
  };

  // handle enable alarm clock
  const startAlarm = () => {
    const now = moment(new Date(), 'HH:mm:ss');
    const target = moment(Object.values(targetTime).join(':') + ':00', 'HH:mm:ss');
    const durations = moment.duration(now.diff(target));

    setCountDownTime({
      hours: Math.abs(durations.hours()),
      minutes: Math.abs(durations.minutes()),
      second: Math.abs(durations.seconds()),
    });
    setEnable(true);
  };

  useEffect(() => {
    const today = moment(new Date()).format("hh:mm");
    const currentCD = moment(Object.values(targetTime).join(':'), 'hh:mm').format('hh:mm');

    if (today === currentCD) {
      console.log('equal')
      resetAlarm();
    }
  }, [secs, hrs, mins, targetTime]);

  // reset alarm clock
  const resetAlarm = () => {
    setEnable(false);
    setSearchText('');
    setCountDownTime({ hours: 0, minutes: 0, second: 0 });
  };

  return (
    <div>
      <title>Clocks App</title>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        sx={{
          paddingTop: '30px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <Clock>
          <Testing
            enable={enable}
            hoursMinSecs={{
              hours: hrs,
              minutes: mins,
              seconds: secs,
            }}
          />
        </Clock>
        {<h3 className="countdown">{/* <Countdown millisecond={millisecond} /> */}</h3>}
        <Box sx={{ marginTop: '30px' }}>
          <Box sx={{ display: 'flex', alignItems: 'center' }}>
            <h2>Wake me up at</h2>
            <Stack
              direction="row"
              justifyContent="center"
              alignItems="center"
              spacing={2}
              sx={{ marginLeft: '30px' }}
            >
              <div>
                <Select
                  labelId="demo-simple-select-label"
                  id="demo-simple-select"
                  value={targetTime.hours}
                  onChange={(e) => handleChangeTime(e, 'hours')}
                >
                  {hours.map((hour, index) => (
                    <MenuItem key={index} value={hour}>
                      {hour}
                    </MenuItem>
                  ))}
                </Select>
              </div>
              <span style={{ fontWeight: 'bold', fontSize: '21px' }}>:</span>
              <div>
                <Select
                  labelId="demo-simple-select-label"
                  id="demo-simple-select"
                  value={targetTime.minutes}
                  onChange={(e) => handleChangeTime(e, 'minutes')}
                >
                  {minutes.map((minute, index) => (
                    <MenuItem key={index} value={minute}>
                      {minute}
                    </MenuItem>
                  ))}
                </Select>
              </div>
            </Stack>
          </Box>
        </Box>
        <Box sx={{ marginTop: '30px' }}>
          <Stack direction="row" alignItems="center" spacing={2}>
            <span>with</span>
            <TextField
              placeholder="Youtube URL or Search Term"
              value={searchText}
              onChange={handleChange}
              sx={{ width: 300 }}
            />
          </Stack>
        </Box>

        {/* Video */}

        {enable ? (
          <Button
            sx={{
              marginTop: 10,
              textTransform: 'capitalize',
              fontWeight: 'bold',
              fontSize: '20px',
            }}
            size="large"
            variant="contained"
            onClick={resetAlarm}
          >
            Disable Alarm
          </Button>
        ) : (
          <Button
            sx={{
              marginTop: 10,
              textTransform: 'capitalize',
              fontWeight: 'bold',
              fontSize: '20px',
            }}
            size="large"
            variant="contained"
            onClick={startAlarm}
          >
            Enable Alarm
          </Button>
        )}
      </Container>
    </div>
  );
};

export default Home;
