import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import moment from 'moment';
// import TimePicker from '@mui/lab/TimePicker';
// import AdapterDateFns from '@mui/lab/AdapterDateFns';
// import LocalizationProvider from '@mui/lab/LocalizationProvider';
import { ChangeEvent, useEffect, useState } from 'react';
import { Box, Container, Typography, TextField, Stack, Button } from '@mui/material';

const Home: NextPage = () => {
  const [time, setTime] = useState<Date | null>(new Date());
  const [enable, setEnable] = useState<boolean>(false);
  const [currentTime, setCurrentTime] = useState<any>('');
  const [searchText, setSearchText] = useState<string>('');

  useEffect(() => {
    setCurrentTime(new Date().toISOString());
  }, []);

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setSearchText(e.target.value);
  };

  const handleChangeTime = (val: Date | null) => {
    console.log(val);
  };

  const toggleAlarm = () => {
    if (enable) resetTimer();
    return setEnable((val) => !val);
  };

  const pauseTimer = () => {
    // resetInterval
  }

  const resetTimer = () => {
    console.log('reset');
    setCurrentTime(new Date().toISOString());
  };

  return (
    <div>
      <title>Clocks App</title>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        sx={{
          paddingTop: '30px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <Box
          sx={{
            width: 300,
            height: 100,
            textAlign: 'center',
            backgroundColor: 'blue',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Typography color="#fff" variant="h3">
            {moment(currentTime).format('hh:mm:ss')}
          </Typography>
        </Box>
        <Box sx={{ marginTop: '30px' }}>
          <Box sx={{ display: 'flex', alignItems: 'center' }}>
            <h2>Wake me up at</h2>
            {/* <LocalizationProvider dateAdapter={AdapterDateFns}>
              <TimePicker
                value={time}
                onChange={handleChangeTime}
                renderInput={(params) => <TextField {...params} />}
              />
            </LocalizationProvider> */}
          </Box>
        </Box>
        <Box sx={{ marginTop: '30px' }}>
          <Stack direction="row" alignItems="center" spacing={2}>
            <span>with</span>
            <TextField
              placeholder="Youtube URL or Search Term"
              value={searchText}
              onChange={handleChange}
              sx={{ width: 300 }}
            />
          </Stack>
        </Box>

        {/* Video */}
        <Button
          sx={{
            marginTop: 10,
            textTransform: 'capitalize',
            fontWeight: 'bold',
            fontSize: '20px',
          }}
          size="large"
          variant="contained"
          onClick={toggleAlarm}
        >
          {enable ? 'Disable Alarm' : 'Enable Alarm'}
        </Button>
      </Container>
    </div>
  );
};

export default Home;
